name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # 监听 main 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 拉取代码

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # 匹配项目所需 Node 版本

      - name: Install pnpm
        run: npm install -g pnpm  # 安装 pnpm

      - name: Install dependencies
        run: pnpm install  # 安装项目依赖

      - name: Build
        run: pnpm run build  # 执行构建

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # 部署到 gh-pages 分支
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的 Token
          publish_dir: ./dist  # 构建产物目录